name: Publish Sigma SDK

on:
  push:
    tags:
      - 'v*.*.*'          # v1.0.0, v1.1.3 …
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Ставим JDK 21 (Temurin) + кэш Gradle
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # 3. Подтягиваем Android SDK / build-tools
      - uses: android-actions/setup-android@v3

      # 4. Ставим Gradle 8.7 (или нужную вам версию) — без wrapper
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7          # зафиксированная версия

      # 5. Собираем .aar и публикуем в GitHub Packages
      - name: Build & publish to GitHub Packages
        run: gradle :sigma-sdk:publish   # ⚠️ вызываем gradle, а НЕ ./gradlew
