name: Publish Sigma SDK

on:
  push:
    tags: ['v*.*.*']          # Пример: v1.0.0, v1.1.0
  workflow_dispatch:          # Ручной запуск из GitHub UI

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build & publish to GitHub Packages
        env:
          GPR_USER: Kazymbetov
          GH_PACKAGES_PAT_2: ${{ secrets.GH_PACKAGES_PAT_2 }}
        run: |
          echo "⏩ Publishing as $GPR_USER"
          ./gradlew :sigma-sdk:publish
