name: Publish Sigma SDK

on:
  push:
    tags:
      - 'v*.*.*'          # запустится, когда пушишь тег v1.0.0, v1.1.3 и т.п.
  workflow_dispatch:       # позволяет запускать вручную из Actions UI

# минимально нужные права токена GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем исходники репозитория
      - name: Checkout sources
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK 21 (Temurin) + кэш Gradle
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # 3. Ставим Android SDK и build-tools
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 4. Собираем .aar и публикуем в GitHub Packages
      - name: Build & publish to GitHub Packages
        uses: gradle/gradle-build-action@v2   # action сам подтянет Gradle
        with:
          arguments: ":sigma-sdk:publish"     # задача публикации модуля SDK
